/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g
 *     -                            On : 2015-10-07 12:06:32
 *     -                 for the lexer : ARBACLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ARBACLexer.h"
/* ----------------------------------------- */


/** String literals used by ARBACLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x41, 0x44, 0x4D, 0x49, 0x4E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x43, 0x41,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x43, 0x52,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x46, 0x41, 0x4C, 0x53, 0x45,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x4E, 0x45, 0x57,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x4E, 0x45, 0x57, 0x55, 0x53, 0x45, 0x52, 0x53,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x4E, 0x65, 0x77, 0x75, 0x73, 0x65, 0x72, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x52, 0x4F, 0x4C, 0x45, 0x53,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x52, 0x6F, 0x6C, 0x65, 0x73,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x53, 0x50, 0x45, 0x43,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x54, 0x52, 0x55, 0x45,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x55, 0x41,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x55, 0x53, 0x45, 0x52, 0x53,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x55, 0x73, 0x65, 0x72, 0x73,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pARBACLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pARBACLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pARBACLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pARBACLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__12    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__13    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__14    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__15    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__16    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__17    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__20    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__21    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__22    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__23    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__24    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mT__25    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mLANGLE    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mRANGLE    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMA    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mCONJUNCTION    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mNOT    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mSEMI    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pARBACLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pARBACLexer ctx);
static void	ARBACLexerFree(pARBACLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ARBACLexerFree  (pARBACLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
ARBACLexerReset (pARBACLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ARBACLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pARBACLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pARBACLexer ARBACLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ARBACLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ARBACLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pARBACLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pARBACLexer ARBACLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pARBACLexer ctx; // Context structure we will build and return

    ctx = (pARBACLexer) ANTLR3_CALLOC(1, sizeof(ARBACLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ARBACLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ARBACLexer interface
     */
    ctx->mT__12	= mT__12;
    ctx->mT__13	= mT__13;
    ctx->mT__14	= mT__14;
    ctx->mT__15	= mT__15;
    ctx->mT__16	= mT__16;
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mID	= mID;
    ctx->mLANGLE	= mLANGLE;
    ctx->mRANGLE	= mRANGLE;
    ctx->mCOMMA	= mCOMMA;
    ctx->mCONJUNCTION	= mCONJUNCTION;
    ctx->mNOT	= mNOT;
    ctx->mSEMI	= mSEMI;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ARBACLexerFree;
    ctx->reset          = ARBACLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( 'ADMIN' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__12
 *
 * Looks to match the characters the constitute the token T__12
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__12(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__12;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:7:7: ( 'ADMIN' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:7:9: 'ADMIN'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__12Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__12Ex; /* Prevent compiler warnings */
    ruleT__12Ex: ;

}
// $ANTLR end T__12

//   Comes from: 8:7: ( 'CA' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__13
 *
 * Looks to match the characters the constitute the token T__13
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__13(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__13;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:8:7: ( 'CA' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:8:9: 'CA'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__13Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__13Ex; /* Prevent compiler warnings */
    ruleT__13Ex: ;

}
// $ANTLR end T__13

//   Comes from: 9:7: ( 'CR' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__14
 *
 * Looks to match the characters the constitute the token T__14
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__14(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__14;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:9:7: ( 'CR' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:9:9: 'CR'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleT__14Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__14Ex; /* Prevent compiler warnings */
    ruleT__14Ex: ;

}
// $ANTLR end T__14

//   Comes from: 10:7: ( 'FALSE' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__15
 *
 * Looks to match the characters the constitute the token T__15
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__15(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__15;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:10:7: ( 'FALSE' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:10:9: 'FALSE'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleT__15Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__15Ex; /* Prevent compiler warnings */
    ruleT__15Ex: ;

}
// $ANTLR end T__15

//   Comes from: 11:7: ( 'NEW' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__16
 *
 * Looks to match the characters the constitute the token T__16
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__16(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__16;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:11:7: ( 'NEW' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:11:9: 'NEW'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleT__16Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__16Ex; /* Prevent compiler warnings */
    ruleT__16Ex: ;

}
// $ANTLR end T__16

//   Comes from: 12:7: ( 'NEWUSERS' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:12:7: ( 'NEWUSERS' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:12:9: 'NEWUSERS'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 13:7: ( 'Newusers' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:13:7: ( 'Newusers' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:13:9: 'Newusers'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 14:7: ( 'ROLES' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:14:7: ( 'ROLES' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:14:9: 'ROLES'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 15:7: ( 'Roles' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:15:7: ( 'Roles' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:15:9: 'Roles'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 16:7: ( 'SPEC' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:16:7: ( 'SPEC' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:16:9: 'SPEC'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 17:7: ( 'TRUE' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:17:7: ( 'TRUE' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:17:9: 'TRUE'
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 18:7: ( 'UA' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:18:7: ( 'UA' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:18:9: 'UA'
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 19:7: ( 'USERS' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:19:7: ( 'USERS' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:19:9: 'USERS'
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 20:7: ( 'Users' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:20:7: ( 'Users' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:20:9: 'Users'
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 234:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:234:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:234:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleIDEx;
        }


        // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:234:31: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1)
            {
        	case 1:
        	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 236:8: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LANGLE
 *
 * Looks to match the characters the constitute the token LANGLE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLANGLE(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LANGLE;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:236:8: ( '<' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:236:10: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleLANGLEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLANGLEEx; /* Prevent compiler warnings */
    ruleLANGLEEx: ;

}
// $ANTLR end LANGLE

//   Comes from: 238:8: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RANGLE
 *
 * Looks to match the characters the constitute the token RANGLE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRANGLE(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RANGLE;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:238:8: ( '>' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:238:10: '>'
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleRANGLEEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRANGLEEx; /* Prevent compiler warnings */
    ruleRANGLEEx: ;

}
// $ANTLR end RANGLE

//   Comes from: 240:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMA
 *
 * Looks to match the characters the constitute the token COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMA(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMA;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:240:7: ( ',' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:240:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleCOMMAEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMAEx; /* Prevent compiler warnings */
    ruleCOMMAEx: ;

}
// $ANTLR end COMMA

//   Comes from: 242:13: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CONJUNCTION
 *
 * Looks to match the characters the constitute the token CONJUNCTION
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCONJUNCTION(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CONJUNCTION;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:242:13: ( '&' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:242:15: '&'
    {
        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleCONJUNCTIONEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCONJUNCTIONEx; /* Prevent compiler warnings */
    ruleCONJUNCTIONEx: ;

}
// $ANTLR end CONJUNCTION

//   Comes from: 244:5: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NOT
 *
 * Looks to match the characters the constitute the token NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNOT(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NOT;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:244:5: ( '-' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:244:7: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleNOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNOTEx; /* Prevent compiler warnings */
    ruleNOTEx: ;

}
// $ANTLR end NOT

//   Comes from: 246:6: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start SEMI
 *
 * Looks to match the characters the constitute the token SEMI
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSEMI(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = SEMI;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:246:6: ( ';' )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:246:8: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleSEMIEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSEMIEx; /* Prevent compiler warnings */
    ruleSEMIEx: ;

}
// $ANTLR end SEMI

//   Comes from: 248:4: ( ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pARBACLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:248:4: ( ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+ )
    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:248:6: ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+
    {
        // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:248:6: ( ' ' | '\\t' | '\\n' | '\\r' | '\\f' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\f':
        	case '\r':
        	case ' ':
        		{
        			alt2=1;
        		}
        	    break;

        	}

        	switch (alt2)
        	{
        	    case 1:
        	        // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel = HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pARBACLexer ctx)
{
    {
        //  /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:8: ( T__12 | T__13 | T__14 | T__15 | T__16 | T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | ID | LANGLE | RANGLE | COMMA | CONJUNCTION | NOT | SEMI | WS )

        ANTLR3_UINT32 alt3;

        alt3=22;

        switch ( LA(1) )
        {
        case 'A':
        	{
        		switch ( LA(2) )
        		{
        		case 'D':
        			{
        				switch ( LA(3) )
        				{
        				case 'M':
        					{
        						switch ( LA(4) )
        						{
        						case 'I':
        							{
        								switch ( LA(5) )
        								{
        								case 'N':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt3=15;
        											}
        										    break;

        										default:
        										    alt3=1;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'C':
        	{
        		switch ( LA(2) )
        		{
        		case 'A':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case '_':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt3=15;
        					}
        				    break;

        				default:
        				    alt3=2;
        				}

        			}
        		    break;
        		case 'R':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case '_':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt3=15;
        					}
        				    break;

        				default:
        				    alt3=3;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'F':
        	{
        		switch ( LA(2) )
        		{
        		case 'A':
        			{
        				switch ( LA(3) )
        				{
        				case 'L':
        					{
        						switch ( LA(4) )
        						{
        						case 'S':
        							{
        								switch ( LA(5) )
        								{
        								case 'E':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt3=15;
        											}
        										    break;

        										default:
        										    alt3=4;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'N':
        	{
        		switch ( LA(2) )
        		{
        		case 'E':
        			{
        				switch ( LA(3) )
        				{
        				case 'W':
        					{
        						switch ( LA(4) )
        						{
        						case 'U':
        							{
        								switch ( LA(5) )
        								{
        								case 'S':
        									{
        										switch ( LA(6) )
        										{
        										case 'E':
        											{
        												switch ( LA(7) )
        												{
        												case 'R':
        													{
        														switch ( LA(8) )
        														{
        														case 'S':
        															{
        																switch ( LA(9) )
        																{
        																case '0':
        																case '1':
        																case '2':
        																case '3':
        																case '4':
        																case '5':
        																case '6':
        																case '7':
        																case '8':
        																case '9':
        																case 'A':
        																case 'B':
        																case 'C':
        																case 'D':
        																case 'E':
        																case 'F':
        																case 'G':
        																case 'H':
        																case 'I':
        																case 'J':
        																case 'K':
        																case 'L':
        																case 'M':
        																case 'N':
        																case 'O':
        																case 'P':
        																case 'Q':
        																case 'R':
        																case 'S':
        																case 'T':
        																case 'U':
        																case 'V':
        																case 'W':
        																case 'X':
        																case 'Y':
        																case 'Z':
        																case '_':
        																case 'a':
        																case 'b':
        																case 'c':
        																case 'd':
        																case 'e':
        																case 'f':
        																case 'g':
        																case 'h':
        																case 'i':
        																case 'j':
        																case 'k':
        																case 'l':
        																case 'm':
        																case 'n':
        																case 'o':
        																case 'p':
        																case 'q':
        																case 'r':
        																case 's':
        																case 't':
        																case 'u':
        																case 'v':
        																case 'w':
        																case 'x':
        																case 'y':
        																case 'z':
        																	{
        																		alt3=15;
        																	}
        																    break;

        																default:
        																    alt3=6;
        																}

        															}
        														    break;

        														default:
        														    alt3=15;
        														}

        													}
        												    break;

        												default:
        												    alt3=15;
        												}

        											}
        										    break;

        										default:
        										    alt3=15;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt3=15;
        							}
        						    break;

        						default:
        						    alt3=5;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'w':
        					{
        						switch ( LA(4) )
        						{
        						case 'u':
        							{
        								switch ( LA(5) )
        								{
        								case 's':
        									{
        										switch ( LA(6) )
        										{
        										case 'e':
        											{
        												switch ( LA(7) )
        												{
        												case 'r':
        													{
        														switch ( LA(8) )
        														{
        														case 's':
        															{
        																switch ( LA(9) )
        																{
        																case '0':
        																case '1':
        																case '2':
        																case '3':
        																case '4':
        																case '5':
        																case '6':
        																case '7':
        																case '8':
        																case '9':
        																case 'A':
        																case 'B':
        																case 'C':
        																case 'D':
        																case 'E':
        																case 'F':
        																case 'G':
        																case 'H':
        																case 'I':
        																case 'J':
        																case 'K':
        																case 'L':
        																case 'M':
        																case 'N':
        																case 'O':
        																case 'P':
        																case 'Q':
        																case 'R':
        																case 'S':
        																case 'T':
        																case 'U':
        																case 'V':
        																case 'W':
        																case 'X':
        																case 'Y':
        																case 'Z':
        																case '_':
        																case 'a':
        																case 'b':
        																case 'c':
        																case 'd':
        																case 'e':
        																case 'f':
        																case 'g':
        																case 'h':
        																case 'i':
        																case 'j':
        																case 'k':
        																case 'l':
        																case 'm':
        																case 'n':
        																case 'o':
        																case 'p':
        																case 'q':
        																case 'r':
        																case 's':
        																case 't':
        																case 'u':
        																case 'v':
        																case 'w':
        																case 'x':
        																case 'y':
        																case 'z':
        																	{
        																		alt3=15;
        																	}
        																    break;

        																default:
        																    alt3=7;
        																}

        															}
        														    break;

        														default:
        														    alt3=15;
        														}

        													}
        												    break;

        												default:
        												    alt3=15;
        												}

        											}
        										    break;

        										default:
        										    alt3=15;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'R':
        	{
        		switch ( LA(2) )
        		{
        		case 'O':
        			{
        				switch ( LA(3) )
        				{
        				case 'L':
        					{
        						switch ( LA(4) )
        						{
        						case 'E':
        							{
        								switch ( LA(5) )
        								{
        								case 'S':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt3=15;
        											}
        										    break;

        										default:
        										    alt3=8;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'l':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 's':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt3=15;
        											}
        										    break;

        										default:
        										    alt3=9;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'S':
        	{
        		switch ( LA(2) )
        		{
        		case 'P':
        			{
        				switch ( LA(3) )
        				{
        				case 'E':
        					{
        						switch ( LA(4) )
        						{
        						case 'C':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt3=15;
        									}
        								    break;

        								default:
        								    alt3=10;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'T':
        	{
        		switch ( LA(2) )
        		{
        		case 'R':
        			{
        				switch ( LA(3) )
        				{
        				case 'U':
        					{
        						switch ( LA(4) )
        						{
        						case 'E':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt3=15;
        									}
        								    break;

        								default:
        								    alt3=11;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'U':
        	{
        		switch ( LA(2) )
        		{
        		case 'A':
        			{
        				switch ( LA(3) )
        				{
        				case '0':
        				case '1':
        				case '2':
        				case '3':
        				case '4':
        				case '5':
        				case '6':
        				case '7':
        				case '8':
        				case '9':
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case '_':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt3=15;
        					}
        				    break;

        				default:
        				    alt3=12;
        				}

        			}
        		    break;
        		case 'S':
        			{
        				switch ( LA(3) )
        				{
        				case 'E':
        					{
        						switch ( LA(4) )
        						{
        						case 'R':
        							{
        								switch ( LA(5) )
        								{
        								case 'S':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt3=15;
        											}
        										    break;

        										default:
        										    alt3=13;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;
        		case 's':
        			{
        				switch ( LA(3) )
        				{
        				case 'e':
        					{
        						switch ( LA(4) )
        						{
        						case 'r':
        							{
        								switch ( LA(5) )
        								{
        								case 's':
        									{
        										switch ( LA(6) )
        										{
        										case '0':
        										case '1':
        										case '2':
        										case '3':
        										case '4':
        										case '5':
        										case '6':
        										case '7':
        										case '8':
        										case '9':
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case '_':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt3=15;
        											}
        										    break;

        										default:
        										    alt3=14;
        										}

        									}
        								    break;

        								default:
        								    alt3=15;
        								}

        							}
        						    break;

        						default:
        						    alt3=15;
        						}

        					}
        				    break;

        				default:
        				    alt3=15;
        				}

        			}
        		    break;

        		default:
        		    alt3=15;
        		}

        	}
            break;
        case 'B':
        case 'D':
        case 'E':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'O':
        case 'P':
        case 'Q':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt3=15;
        	}
            break;
        case '<':
        	{
        		alt3=16;
        	}
            break;
        case '>':
        	{
        		alt3=17;
        	}
            break;
        case ',':
        	{
        		alt3=18;
        	}
            break;
        case '&':
        	{
        		alt3=19;
        	}
            break;
        case '-':
        	{
        		alt3=20;
        	}
            break;
        case ';':
        	{
        		alt3=21;
        	}
            break;
        case '\t':
        case '\n':
        case '\f':
        case '\r':
        case ' ':
        	{
        		alt3=22;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 3;
            EXCEPTION->state        = 0;


            goto ruleTokensEx;

        }

        switch (alt3)
        {
    	case 1:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:10: T__12
    	    {
    	        /* 1:10: T__12 */
    	        mT__12(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:16: T__13
    	    {
    	        /* 1:16: T__13 */
    	        mT__13(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:22: T__14
    	    {
    	        /* 1:22: T__14 */
    	        mT__14(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:28: T__15
    	    {
    	        /* 1:28: T__15 */
    	        mT__15(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:34: T__16
    	    {
    	        /* 1:34: T__16 */
    	        mT__16(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:40: T__17
    	    {
    	        /* 1:40: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:46: T__18
    	    {
    	        /* 1:46: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:52: T__19
    	    {
    	        /* 1:52: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:58: T__20
    	    {
    	        /* 1:58: T__20 */
    	        mT__20(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:64: T__21
    	    {
    	        /* 1:64: T__21 */
    	        mT__21(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:70: T__22
    	    {
    	        /* 1:70: T__22 */
    	        mT__22(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:76: T__23
    	    {
    	        /* 1:76: T__23 */
    	        mT__23(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:82: T__24
    	    {
    	        /* 1:82: T__24 */
    	        mT__24(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:88: T__25
    	    {
    	        /* 1:88: T__25 */
    	        mT__25(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:94: ID
    	    {
    	        /* 1:94: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:97: LANGLE
    	    {
    	        /* 1:97: LANGLE */
    	        mLANGLE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:104: RANGLE
    	    {
    	        /* 1:104: RANGLE */
    	        mRANGLE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:111: COMMA
    	    {
    	        /* 1:111: COMMA */
    	        mCOMMA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:117: CONJUNCTION
    	    {
    	        /* 1:117: CONJUNCTION */
    	        mCONJUNCTION(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:129: NOT
    	    {
    	        /* 1:129: NOT */
    	        mNOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:133: SEMI
    	    {
    	        /* 1:133: SEMI */
    	        mSEMI(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /home/trucnguyenlam/ides/antlr/workspace/ARBACFinal/src/ARBAC.g:1:138: WS
    	    {
    	        /* 1:138: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
