./vac.sh ../regression/original/Hospital/Hospital1.arbac --backend=mucke
./vac.sh ../regression/original/Hospital/Hospital2.arbac --backend=mucke
./vac.sh ../regression/original/Hospital/Hospital3.arbac --backend=mucke
./vac.sh ../regression/original/Hospital/Hospital4.arbac --backend=mucke
./vac.sh ../regression/original/Hospital/Hospital1.arbac --backend=mucke --no-pruning
./vac.sh ../regression/original/Hospital/Hospital2.arbac --backend=mucke --no-pruning
./vac.sh ../regression/original/Hospital/Hospital3.arbac --backend=mucke --no-pruning
./vac.sh ../regression/original/Hospital/Hospital4.arbac --backend=mucke --no-pruning

./vac.sh ../regression/original/University/University1.arbac --backend=mucke
./vac.sh ../regression/original/University/University2.arbac --backend=mucke
./vac.sh ../regression/original/University/University3.arbac --backend=mucke
./vac.sh ../regression/original/University/University4.arbac --backend=mucke
./vac.sh ../regression/original/University/University1.arbac --backend=mucke --no-pruning
./vac.sh ../regression/original/University/University2.arbac --backend=mucke --no-pruning
./vac.sh ../regression/original/University/University3.arbac --backend=mucke --no-pruning
./vac.sh ../regression/original/University/University4.arbac --backend=mucke --no-pruning

./vac.sh ../regression/original/Bank/Bank1.arbac --backend=mucke
./vac.sh ../regression/original/Bank/Bank2.arbac --backend=mucke
./vac.sh ../regression/original/Bank/Bank3.arbac --backend=mucke
./vac.sh ../regression/original/Bank/Bank4.arbac --backend=mucke
# ./vac.sh ../regression/original/Bank/Bank1.arbac --backend=mucke --no-pruning
# ./vac.sh ../regression/original/Bank/Bank2.arbac --backend=mucke --no-pruning
# ./vac.sh ../regression/original/Bank/Bank3.arbac --backend=mucke --no-pruning
# ./vac.sh ../regression/original/Bank/Bank4.arbac --backend=mucke --no-pruning

./vac.sh ../regression/stefano/minified.arbac        --backend=mucke
./vac.sh ../regression/stefano/prova.arbac           --backend=mucke
./vac.sh ../regression/stefano/safe.arbac            --backend=mucke
./vac.sh ../regression/stefano/test.arbac            --backend=mucke
./vac.sh ../regression/stefano/test_unsafe.arbac      --backend=mucke
./vac.sh ../regression/stefano/troubles.arbac        --backend=mucke
./vac.sh ../regression/stefano/minified.arbac        --backend=mucke --no-pruning
./vac.sh ../regression/stefano/prova.arbac           --backend=mucke --no-pruning
./vac.sh ../regression/stefano/safe.arbac            --backend=mucke --no-pruning
./vac.sh ../regression/stefano/test.arbac            --backend=mucke --no-pruning
./vac.sh ../regression/stefano/test_unsafe.arbac      --backend=mucke --no-pruning
./vac.sh ../regression/stefano/troubles.arbac        --backend=mucke --no-pruning

./vac.sh ../regression/testcases/mixed/test1.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test2.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test3.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test4.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test5.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test6.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test7.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test8.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test9.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test10.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixed/test1.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/mixed/test2.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/mixed/test3.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/mixed/test4.arbac   --backend=mucke  --no-pruning
# ./vac.sh ../regression/testcases/mixed/test5.arbac   --backend=mucke  --no-pruning

./vac.sh ../regression/testcases/mixednocr/test1.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test2.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test3.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test4.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test5.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test6.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test7.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test8.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test9.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test10.arbac   --backend=mucke
./vac.sh ../regression/testcases/mixednocr/test1.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/mixednocr/test2.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/mixednocr/test3.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/mixednocr/test4.arbac   --backend=mucke  --no-pruning
# ./vac.sh ../regression/testcases/mixednocr/test5.arbac   --backend=mucke  --no-pruning

./vac.sh ../regression/testcases/positive/test1.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test2.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test3.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test4.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test5.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test6.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test7.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test8.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test9.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test10.arbac   --backend=mucke
./vac.sh ../regression/testcases/positive/test1.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/positive/test2.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/positive/test3.arbac   --backend=mucke  --no-pruning
./vac.sh ../regression/testcases/positive/test4.arbac   --backend=mucke  --no-pruning
# ./vac.sh ../regression/testcases/positive/test5.arbac   --backend=mucke  --no-pruning
